// app/renderer/Tasks/CalendarWindow.vue
<template>
    <div class="CalendarWindow">
        <MainMenu v-if="!weekKey"></MainMenu>
        <br v-if="!weekKey"/>
        <div>
            <div v-for="(week, week_key) of weeks" class="Week" :data-week="week_key">
                <div v-for="(dayCode) of week.days" class="Day"
                     @click="open(dayCode)"
                     @mouseenter="store.calendarHoveredDayCode(dayCode)"
                     @mouseleave="store.calendarHoveredDayCode(null)"
                     :title="days[dayCode].dayCode"
                     :class="{
                         is_today: days[dayCode].isToday,
                         is_current_month: days[dayCode].isCurrentMonth,
                         is_opened: days[dayCode].isOpened,
                         is01: days[dayCode].isFirstDayOfTheMonth,
                         is_weekend: days[dayCode].isWeekend,
                         ['is_special_day_' + specialDays[dayCode]]: !!specialDays[dayCode],
                    }">
                    <span class="DayTitle">{{ days[dayCode].title }}</span>
                    <span class="TimeCharged">{{ days[dayCode].charged_seconds_text }}</span>
                </div>
                <span class="MonthTimeCharged" v-if="months[week_key] && months[week_key].month_charged_seconds">
                    <span class="_Week" v-if="week.week_charged">&Sigma; {{ week.week_charged_text }}</span><br/>
                    <span class="_Month">{{ months[week_key].month_title }}:
                        <span
                            :class="{ MonthOvertime: months[week_key].month_overtime_seconds > 0, MonthOvertimeWarning: months[week_key].month_overtime_seconds >= 7200 }"
                            :title="months[week_key].month_overtime_text">
                            {{ months[week_key].month_charged_seconds_text }}
                        </span>
                    </span>
                </span>
                <span class="WeekTimeCharged" v-if="!months[week_key] && week.week_charged">&Sigma; {{ week.week_charged_text }}</span>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
    import {Component, Prop, Vue} from "vue-facing-decorator";
    import store from "../Store/Store";
    import Store_GetCalendarStatistics from "../Store/Store_GetCalendarStatistics";
    import createCalendarMenu from "./CalendarMenu";
    import MainMenu from "../MainMenu.vue";

    const remote = window.remote;

    @Component({
        components: {MainMenu}
    })
    export default class CalendarWindow extends Vue {

        cache = null;

        @Prop({type: String}) weekKey;

        get store() {
            return store;
        }

        get weeks() {
            this.collect_data();

            if (this.weekKey) {
                if (this.cache.weeks[this.weekKey]) {
                    return {
                        weekKey: this.cache.weeks[this.weekKey],
                    }
                }
                return {}; // do not show anything if week was requested but not found
            }
            return this.cache.weeks;
        }

        get months() {
            this.collect_data();

            return this.cache.months;
        }

        get days() {
            this.collect_data();

            return this.cache.days;
        }

        get specialDays() {
            return store.state.settings['special_days'] || {};
        }

        collect_data() {
            if (this.cache) {
                return;
            }

            this.cache = Store_GetCalendarStatistics();
        }

        open(day) {
            store.setDay(day);
            store.returnToTasksScreen();
        }

        created() {
            store.setFileTotals(window.ipc.sendSync('tasks.getFileTotals'));
        }

        mounted() {
            if (this.weekKey) {
                return;
            }
            window.addEventListener('contextmenu', this.calendarMenuShow, false);
        }

        beforeUnmount() {
            if (this.weekKey) {
                return;
            }
            window.removeEventListener('contextmenu', this.calendarMenuShow);
        }

        calendarMenuShow(e) {
            e.preventDefault();
            createCalendarMenu(() => this.cache = null).popup({window: remote.getCurrentWindow()})
        }
    }
</script>

<style scoped lang="scss">
    .CalendarWindow {
        overflow-y: auto;
        max-height: 100%;

        .Week {
            display: flex;

            .MonthTimeCharged {
                line-height: 13px;
                padding-left: 5px;
                color: grey;
                padding-top: 3px;

                ._Month {
                    color: #bebebe;
                }

                .MonthOvertime {
                    color: #8a4444;
                }

                .MonthOvertimeWarning {
                    color: #b30e0d;
                }
            }

            .WeekTimeCharged {
                line-height: 29px;
                padding-left: 5px;
                color: grey;
            }
        }

        .Day {
            border: 1px solid #f5f5f5;
            width: 54px;
            height: 30px;
            padding: 1px 4px;
            position: relative;
            cursor: pointer;

            color: #a2a2a2;

            &.is_weekend {
                color: #d0d0d0;
            }

            &.is_current_month {
                color: black;
                border: 1px solid #bdbdbd;

                &.is_weekend {
                    color: #9c9c9c;
                    border-color: #e4e4e4;
                }
            }

            &.is_today {
                border-color: #00c4ff;
            }

            &.is01 {
                border-left-color: #8e8e8e !important;
                border-bottom-color: #8e8e8e !important;
            }

            &.is_special_day_vacation {
                color: #8b26b6 !important;
                background-color: #f9ecff;
            }

            &.is_special_day_holiday {
                color: green !important;
                background-color: #f2fff3;
            }

            &.is_special_day_shortday,
            &.is_special_day_workday {
                color: black !important;

                &.is_special_day_shortday {
                    color: green !important;
                }

                &.is_current_month {
                    border-color: #bdbdbd;
                }
            }

            &.is_special_day_unpaid {
                background-color: #efefef;
                text-decoration: line-through;
            }

            &:hover {
                background-color: #e6faff;
                border-color: #b6c8ca !important;
            }

            &.is_opened {
                border-color: black !important;
            }

            &:hover,
            &.is_opened {
                border-width: 2px;
                padding: 0 3px;

                .TimeCharged {
                    right: 1px;
                    bottom: -2px;
                }
            }

            .DayTitle {

            }

            .TimeCharged {
                position: absolute;
                right: 2px;
                bottom: -1px;
                color: grey;
                font-size: smaller;
            }
        }
    }
</style>

// app/renderer/Tasks/CalendarWindow.tsx
import React, {useEffect, useState} from 'react';
import {useStoreContext} from '../Store/Store';
import Store_GetCalendarStatistics from '../Store/Store_GetCalendarStatistics';
import createCalendarMenu from './CalendarMenu';

const {remote} = window;

const CalendarWindow = ({weekKey}) => {
    const store = useStoreContext();
    const [cache, setCache] = useState(null);

    const collectData = () => {
        if (cache) return;
        setCache(Store_GetCalendarStatistics());
    };

    const open = (day) => {
        store.setDay(day);
        store.returnToTasksScreen();
    };

    const calendarMenuShow = (e) => {
        e.preventDefault();
        createCalendarMenu(store, () => setCache(null)).popup({window: remote.getCurrentWindow()});
    };

    useEffect(() => {
        store.setFileTotals(window.ipc.sendSync('tasks.getFileTotals'));
        if (!weekKey) {
            window.addEventListener('contextmenu', calendarMenuShow, false);
        }
        return () => {
            if (!weekKey) {
                window.removeEventListener('contextmenu', calendarMenuShow);
            }
        };
    }, [weekKey]);

    collectData();

    const weeks = weekKey ? (cache?.weeks[weekKey] ? {[weekKey]: cache.weeks[weekKey]} : {}) : cache?.weeks;
    const months = cache?.months;
    const days = cache?.days;
    const specialDays = store.state.settings['special_days'] || {};

    if (!weeks) {
        return <></>
    }

    return (
        <div className="CalendarWindow">
            <br/>
            <div>
                {Object.entries(weeks).map(([week_key, week]: any) => (
                    <div key={week_key} className="Week" data-week={week_key}>
                        {weekKey && (
                            <a href="#" className="PrevNextButton" onClick={() => open(store.state.day_key_prev_week)}>
                                <i className="icofont-rounded-left"></i>
                            </a>
                        )}
                        {week.days.map((dayCode) => (
                            <div
                                key={dayCode}
                                className={`Day ${
                                    days[dayCode].isToday ? 'is_today' : ''
                                } ${
                                    days[dayCode].isCurrentMonth ? 'is_current_month' : ''
                                } ${
                                    days[dayCode].isOpened ? 'is_opened' : ''
                                } ${
                                    days[dayCode].isFirstDayOfTheMonth ? 'is01' : ''
                                } ${
                                    days[dayCode].isWeekend ? 'is_weekend' : ''
                                } ${
                                    specialDays[dayCode] ? `is_special_day_${specialDays[dayCode]}` : ''
                                }`}
                                onClick={() => open(dayCode)}
                                onMouseEnter={() => store.calendarHoveredDayCode(dayCode)}
                                onMouseLeave={() => store.calendarHoveredDayCode(null)}
                                title={days[dayCode].dayCode}
                            >
                                <span className="DayTitle">{days[dayCode].title}</span>
                                <span className="TimeCharged">{days[dayCode].charged_seconds_text}</span>
                            </div>
                        ))}
                        {weekKey && (
                            <a href="#" className="PrevNextButton" onClick={() => open(store.state.day_key_next_week)}>
                                <i className="icofont-rounded-right"></i>
                            </a>
                        )}
                        {months[week_key] && months[week_key].month_charged_seconds && (
                            <span className="MonthTimeCharged">
                                <span className="_Week">{week.week_charged && `Σ ${week.week_charged_text}`}</span>
                                <br/>
                                <span className="_Month">
                                    {months[week_key].month_title}:
                                    <span
                                        className={`${
                                            months[week_key].month_overtime_seconds > 0 ? 'MonthOvertime' : ''
                                        } ${
                                            months[week_key].month_overtime_seconds >= 7200 ? 'MonthOvertimeWarning' : ''
                                        }`}
                                        title={months[week_key].month_overtime_text}
                                    >
                                        {months[week_key].month_charged_seconds_text}
                                    </span>
                                </span>
                            </span>
                        )}
                        {!months[week_key] && week.week_charged && (
                            <span className="WeekTimeCharged">Σ {week.week_charged_text}</span>
                        )}
                    </div>
                ))}
            </div>
        </div>
    );
};

export default CalendarWindow;
