// app/renderer/Tasks/TaskRow.vue
<template>
    <div class="TRow"
         @mouseenter="store.tasksUiHoveredId(task.id)"
         @mouseleave="store.tasksUiHoveredId(null)"
         :key="task.id"
         :class="{
             selected: task._selected,
             distributed: task.distributed,
             notchargeable: !task.chargeable,
             hovered: store.state.tasksHoveredId === task.id,
             timered: store.state.taskTimeredId === task.id,
             hasRecords: !!task.time_recorded_seconds,
             isDone: !!task.is_done,
             isOnHold: !!task.is_on_hold,
             isRootTask: (rootTasks[task.code || task.id]?.id === task.id),
             isSubtask: !!task.parentId,
             isMissingParent: task.parentId && store.parentIsMissing(task),
         }"
         @click="rowOnClick($event, task)"
    >
        <div class="TRowContent" v-if="!(store.state.tasksHideUnReportable && (task.distributed || !task.chargeable)) || store.state.taskTimeredId === task.id">
            <div class="TCol --hierarchy">
                <template v-if="!task.parentId">
                    <i class="icofont-rounded-down" v-if="task.subtaskIds?.length"></i>
                    <i class="icofont-rounded-right" style="color: #ababab" v-else></i>
                </template>
            </div>
            <div class="TCol --chargeable">
                <i class="IconAsInput icofont-not-allowed" :class="{ active: !task.chargeable }"
                   @click="store.updateTask([task.id, 'chargeable', !task.chargeable])"></i>
            </div>
            <div class="TCol --distributed">
                <i class="IconAsInput icofont-exchange" :class="{ active: task.distributed }"
                   @click="store.updateTask([task.id, 'distributed', !task.distributed])"></i>
            </div>
            <div class="TCol --frozen">
                <i class="IconAsInput icofont-unlock" :class="{ active: task.frozen }"
                   @click="store.updateTask([task.id, 'frozen', !task.frozen])"></i>
            </div>
            <div class="TCol --code"
                 @click="store.state.tasksShowAsReport ? copyToClipboard($event, task.code) : editTask($event, task)">
                <span v-if="rootTasks[task.code]" style="color: #acacac;">{{ task.code }}</span>
                <span v-else>{{ task.code }}</span>
                <div class="--edit-button">
                    <a href="#" @click.stop="editTask($event, task)" v-if="!task.grouped">edit</a>
                </div>
            </div>
            <div class="TCol --title"
                 @click="store.state.tasksShowAsReport ? copyToClipboard($event, task.notes) : editTask($event, task)">
                                <span class="Title--Content"
                                      :class="{ ellipsis: !store.state.tasksShowAsReport && !store.state.tasksHideUnReportable }"><span>
                                    <template v-if="task.code !== 'idle' && !task.asanaTaskGid && !rootTasks[task.code]?.asanaTaskGid">❔</template>
                                    {{ task.title || '&nbsp;' }}
                                </span></span>
                <span class="Note--Content">
                                    <span class="EmptyNotesError" v-if="store.state.tasksShowAsReport && !task.notes">[empty notes]</span>
                                    <span v-else>{{ task.notes || '&nbsp;' }}</span>
                                </span>
                <span class="Comment--Content" v-if="task.comment">
                                    // {{ task.comment || '&nbsp;' }}
                                </span>
            </div>
            <div class="TCol --status">
                <i class="IconAsInput IconDone icofont-ui-check" :class="{ active: task.is_done }"
                   @click="store.updateTask([task.id, 'is_done', !task.is_done])"></i>
                <i class="IconAsInput IconOnHold icofont-sand-clock"
                   :class="{ active: task.is_on_hold }"
                   @click="store.updateTask([task.id, 'is_on_hold', !task.is_on_hold])"></i>
            </div>
            <div class="TCol --timespan"
                 @click="dropTime($event, task)"
                 @mousedown.prevent.stop="emit('drag_start', $event, task)"
                 :title="'Final charge: ' + task.time_charge_text + '\n' + 'Recorded: ' + task.time_recorded_text + '\n' + 'Not recorded: ' + task.time_unrecorded_text"
            >
                            <span class="--timespan-spent">
                                <template v-if="store.state.taskTimeredId === task.id">{{ timespanToText(store.state.timerElapsedSeconds) }}<br /></template>
                                <span style="display: inline" v-if="store.state.taskTimeredId === task.id">&sum; </span>{{ task.time_spent_text }}
                            </span>
                <span class="--timespan-charge"
                      v-if="task.time_recorded_seconds > 0">
                                {{ task.time_unrecorded_text }}
                            </span>
                <span class="--timespan-final-charge">
                                {{ task.time_charge_text }}
                            </span>
                <LineChart class="ChartRecorded bg-dark"
                           :height="3"
                           :total="task.time_charge_seconds"
                           :progress_success="task.time_recorded_seconds"></LineChart>
                <LineChart class="ChartSpent bg-warning"
                           :height="3"
                           :total="task.time_charge_seconds"
                           :progress_normal="task.time_spent_seconds"></LineChart>
            </div>
            <div class="TCol --playback">
                <i class="IconAsInput icofont-square" v-if="store.state.taskTimeredId === task.id"
                   @click="stopTimer()"></i>
                <i class="IconAsInput icofont-play" v-if="store.state.taskTimeredId !== task.id"
                   @click="startTimer($event, task)"></i>
            </div>
        </div>

        <div class="Subtasks">
            <template v-for="subtask_id of task.subtaskIds">
                <TaskRow :group_id="props.group_id"
                         :task_id="subtask_id"
                         :tasks-grouped="props.tasksGrouped"
                         @drag_start="subtaskDragStart"
                ></TaskRow>
            </template>
        </div>
    </div>
</template>

<script setup lang="ts">
    import store from "../Store/Store";
    import LineChart from '../Components/LineChart.vue';
    import {computed} from "vue";
    import timer from "../Timer";
    import {timespanToText} from "../Utils/Utils";

    const props = defineProps<{
        tasksGrouped: Record<string, TaskGroupObj>,
        group_id: string,
        task_id: string,
    }>();

    const emit = defineEmits(['drag_start']);

    const task = computed<TaskObj>(() => {
        return props.tasksGrouped[props.group_id].tasks[props.task_id] || <any>{code: 'ERROR!', title: `Invalid task id '${props.task_id}' in group '${props.group_id}'`};
    })
    const parentTask = computed<TaskObj>(() => {
        return task.value.parentId
            ? props.tasksGrouped[props.group_id].tasks[task.value.parentId]
            : null;
    })

    function rowOnClick($event, task) {
        if ($event.ctrlKey) {
            store.tasksUiToggle(task.id);
        }
    }

    function editTask($event, task) {
        store.taskEdit(task.id);
    }

    function startTimer($event, task) {
        timer.start(task.id);
    }

    function stopTimer() {
        timer.stop();
    }

    const rootTasks = computed(() => {
        const result = {};
        for (let group of Object.values(props.tasksGrouped)) {
            for (let task of Object.values(group.tasks)) {
                if (task.code !== 'idle' && !task.parentId) {
                    result[task.code || task.id] = task;
                }
            }
        }
        return result;
    });

    function copyToClipboard(ev, text: string) {
        navigator.clipboard.writeText(text).then(function () {
            ev.target.classList.add('AnimationPulseOnceAndHide');
        }, function () {
            /* clipboard write failed */
        });
    }

    function dropTime($event, task = null) {
        if (!store.state.drag.active || !store.state.drag.readyToDrop) {
            return;
        }
        store.state.drag.readyToDrop = store.state.drag.active = false;
        store.state.drag.taskTo = task.id;

        if (store.state.drag.minutes > 0 &&
            store.state.drag.taskFrom &&
            store.state.drag.taskTo &&
            store.state.drag.taskFrom !== store.state.drag.taskTo) {
            store.taskAddSession([store.state.drag.taskFrom, -store.state.drag.minutes, 'store.state.drag']);
            store.taskAddSession([store.state.drag.taskTo, store.state.drag.minutes, 'drop']);
        }
        store.dragClear();
    }

    function subtaskDragStart($event: Event, task: TaskObj) {
        emit('drag_start', $event, task);
    }
</script>

<style lang="scss">
</style>

// app/renderer/Tasks/TaskRow.tsx
import {cn} from "@/lib/utils";
import React, {useCallback} from 'react';
import LineChart from '../Components/LineChart';
import {useStoreContext} from '../Store/Store';
import timer from "../Timer";
import {timespanToText} from '../Utils/Utils';

const TaskRow = ({tasksGrouped, group_id, task_id, onDragStart}: any) => {
    const task: TaskObj = tasksGrouped[group_id]?.tasks[task_id] || {code: 'ERROR!', title: `Invalid task id '${task_id}' in group '${group_id}'`};
    const rootTasks: any[] = Object.values(tasksGrouped).flatMap((group: any) => Object.values(group.tasks)).filter((t: any) => t.code !== 'idle' && !t.parentId);
    const store = useStoreContext();

    const editTask = useCallback((event) => {
        store.taskEdit(task.id);
    }, [task.id]);

    const startTimer = useCallback((event) => {
        timer.start(task.id);
    }, [task.id]);

    const stopTimer = useCallback(() => {
        timer.stop();
    }, []);

    const copyToClipboard = useCallback((event, text) => {
        navigator.clipboard.writeText(text).then(() => {
            event.target.classList.add('AnimationPulseOnceAndHide');
        });
    }, []);

    const dropTime = useCallback((event) => {
        store.dropTime(event, task.id);
    }, [store.state, task.id]);

    return (
        <div
            className={cn([
                "TRow",
                task.distributed && 'distributed',
                !task.chargeable && 'notchargeable',
                store.state.tasksHoveredId === task.id && 'hovered',
                store.state.taskTimeredId === task.id && 'timered',
                task.time_recorded_seconds && 'hasRecords',
                task.is_done && 'isDone',
                task.is_on_hold && 'isOnHold',
                rootTasks[task.code || task.id]?.id === task.id && 'isRootTask',
                task.parentId && 'isSubtask',
                task.parentId && store.parentIsMissing(task) && 'isMissingParent',
                task.id === store.state.drag.taskFrom && 'isDragFrom',
            ])}
        >
            <div className="TRowContent" style={{display: (store.state.tasksHideUnReportable && (task.distributed || !task.chargeable)) && store.state.taskTimeredId !== task.id ? 'none' : ''}}
                 onMouseEnter={() => store.tasksUiHoveredId(task.id)}
                 onMouseLeave={() => store.tasksUiUnhoveredId(task.id)}
            >
                <div className="TCol --hierarchy">
                    {!task.parentId ? (
                        task.subtaskIds?.length ? <i className="icofont-rounded-down"></i> : <i className="icofont-rounded-right" style={{color: '#ababab'}}></i>
                    ) : null}
                </div>
                <div className="TCol --chargeable">
                    <i className={`IconAsInput icofont-not-allowed ${!task.chargeable ? 'active' : ''}`} onClick={() => store.updateTask([task.id, 'chargeable', !task.chargeable])}></i>
                </div>
                <div className="TCol --distributed">
                    <i className={`IconAsInput icofont-exchange ${task.distributed ? 'active' : ''}`} onClick={() => store.updateTask([task.id, 'distributed', !task.distributed])}></i>
                </div>
                <div className="TCol --frozen">
                    <i className={`IconAsInput icofont-unlock ${task.frozen ? 'active' : ''}`} onClick={() => store.updateTask([task.id, 'frozen', !task.frozen])}></i>
                </div>
                <div className="TCol --code" onClick={() => store.state.tasksShowAsReport ? copyToClipboard(event, task.code) : editTask(event)}>
                    <span style={{color: rootTasks[task.code] ? '#acacac' : 'inherit'}}>{task.code}</span>
                    <div className="--edit-button">
                        {!task.grouped && <a href="#" onClick={(e) => {
                            e.stopPropagation();
                            editTask(e);
                        }}>edit</a>}
                    </div>
                </div>
                <div className="TCol --title" onClick={() => store.state.tasksShowAsReport ? copyToClipboard(event, task.notes) : editTask(event)}>
                    {(!task.parentId || task.title) && <span className={`Title--Content ${!store.state.tasksShowAsReport && !store.state.tasksHideUnReportable ? 'ellipsis' : ''}`}>
                        {task.code !== 'idle' && !task.asanaTaskGid && !rootTasks[task.code]?.asanaTaskGid && !task.youtrackTaskCode && !task.parentId ? '❔' : null}
                        {task.title || '\u00A0'}
                    </span>}
                    <span className="Note--Content">
                        {store.state.tasksShowAsReport && !task.notes ? '[empty notes]' : task.notes || '\u00A0'}
                    </span>
                    {task.comment && <span className="Comment--Content">{task.comment || '\u00A0'}</span>}
                </div>
                <div className="TCol --status">
                    <i className={`IconAsInput IconDone icofont-ui-check ${task.is_done ? 'active' : ''}`} onClick={() => store.updateTask([task.id, 'is_done', !task.is_done])}></i>
                    <i className={`IconAsInput IconOnHold icofont-sand-clock ${task.is_on_hold ? 'active' : ''}`} onClick={() => store.updateTask([task.id, 'is_on_hold', !task.is_on_hold])}></i>
                </div>
                <div className="TCol --timespan" onClick={(event) => dropTime(event, task)} onMouseDown={(event) => {
                    event.preventDefault();
                    onDragStart(event, task);
                }} title={`Final charge: ${task.time_charge_text}\nRecorded: ${task.time_recorded_text}\nNot recorded: ${task.time_unrecorded_text}`}>
                    <span className="--timespan-spent">
                        {task.id === store.state.drag.taskFrom && store.state.drag.minutes  > 1 && '⇩ '}
                        {store.state.taskTimeredId === task.id ? <div>{timespanToText(store.state.timerElapsedSeconds)}</div> : null}
                        {store.state.taskTimeredId === task.id && <span style={{display: 'inline'}}>&sum; </span>}
                        {task.time_spent_text}
                    </span>
                    {task.time_recorded_seconds > 0 && <span className="--timespan-charge">{task.time_unrecorded_text}</span>}
                    <span className="--timespan-final-charge">{task.time_charge_text}</span>
                    <LineChart className="ChartRecorded bg-dark" height={3} total={task.time_charge_seconds} progress_success={task.time_recorded_seconds}/>
                    <LineChart className="ChartSpent bg-warning" height={3} total={task.time_charge_seconds} progress_normal={task.time_spent_seconds}/>
                </div>
                <div className="TCol --playback">
                    {store.state.taskTimeredId === task.id && <i className={"IconAsInput icofont-square " + (task.is_done || task.is_on_hold ? 'hidden' : '')} onClick={stopTimer}></i>}
                    {store.state.taskTimeredId !== task.id && <i className={"IconAsInput icofont-play " + (task.is_done || task.is_on_hold ? 'hidden' : '')} onClick={(event) => startTimer(event, task)}></i>}
                    {task.is_done && <i className="IconAsInput IconDone IconStatus icofont-ui-check active"></i>}
                    {task.is_on_hold && <i className="IconAsInput IconOnHold IconStatus icofont-sand-clock active"></i>}
                </div>
            </div>

            <div className="Subtasks">
                {Object.values(task.subtaskIds || []).map(subtask_id => (
                    <TaskRow
                        key={subtask_id}
                        group_id={group_id}
                        task_id={subtask_id}
                        tasksGrouped={tasksGrouped}
                        onDragStart={onDragStart}
                    />
                ))}
            </div>
        </div>
    );
};

export default TaskRow;
