// app/renderer/Tasks/TodosWindow.tsx
import React from "react";
import _ from "lodash";
import { useStoreContext } from "../Store/Store";

const TodosWindow = () => {
    const store = useStoreContext();
    const tasks = _.sortBy(store.state.asanaTasks, "assignee_section.name");

    return (
        <div className="TodosWindow">
            <button onClick={() => store.loadAsanaTasks(true)}>Refresh tasks list</button>
            <table>
                <thead>
                    <tr>
                        <th>section</th>
                        <th>name</th>
                    </tr>
                </thead>
                <tbody>
                    {tasks.map((task) => (
                        <tr key={task.gid}>
                            <td style={{ whiteSpace: "nowrap" }}>{task.assignee_section!.name}</td>
                            <td>
                                [
                                <a
                                    href={task.permalink_url}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    view
                                </a>
                                ]{task.name}
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};

export default TodosWindow;

// app/renderer/Tasks/TodosWindow.vue
<template>
    <div class="TodosWindow">
        <button @click="store.loadAsanaTasks(true)">Refresh tasks list</button>
        <table>
            <thead>
            <tr>
                <th>section</th>
                <th>name</th>
            </tr>
            </thead>
            <tbody>
            <template v-for="task of tasks">
                <tr>
                    <td style="white-space: nowrap">
                        {{ task.assignee_section.name }}
                    </td>
                    <td>
                        [<a :href="task.permalink_url" target="_blank">view</a>]
                        {{ task.name }}
                    </td>
                </tr>
            </template>
            </tbody>
        </table>
    </div>
</template>

<script lang="ts" setup>
    import _ from "lodash";
    import {computed, onMounted} from "vue";
    import store from "../Store/Store";

    const tasks = computed(() => {
        return _.sortBy(store.state.asanaTasks, 'assignee_section.name');
    })
</script>

<style scoped lang="scss">
    .TodosWindow {
        display: flex;
        flex-direction: column;
        height: 100%;
        overflow-y: scroll;
    }
</style>
